version: '3.8'

volumes:
  mpc-bytecodes:
  mpc-schedules:

services:
  ethnode:
    image: sbellem/ethdevnode:latest
    ports:
      - "8545:8545"
      - "8546:8546"

  #deploycontract:
  #  image: sbellem/hbswap:go-deps
  #  environment:
  #    #POADIR: /opt/poa
  #    POA_KEYSTORE: /opt/poa/keystore
  #  working_dir: /go/src/github.com/initc3/HoneyBadgerSwap/src/go
  #  entrypoint: ""
  #  command: ["wait-for-it", "ethnode:8545", "--", "go", "run", "deploy/deploy.go", "ethnode"]

  # pre-compiled MPC programs
  mpccompile:
    image: sbellem/hbswapmpcbytecodes
    volumes:
      - mpc-bytecodes:/usr/src/Programs/Bytecode
      - mpc-schedules:/usr/src/Programs/Schedules

  mpcnode0:
    image: sbellem/hbswap
    environment:
      POA_KEYSTORE: /opt/poa/keystore
    ports:
      - 8080:8080
    volumes:
      - mpc-bytecodes:/usr/src/hbswap/Programs/Bytecode
      - mpc-schedules:/usr/src/hbswap/Programs/Schedules
        #- inputmaskshares-p0:/opt/hbswap/inputmask-shares
        #- ppdata-p0:/opt/hbswap/preprocessing-data
        #- persistence-p0:/usr/src/hbswap/Persistence
    secrets:
      - P0.key
    working_dir: /usr/src/hbswap
    # NOTE IMPORTANT!
    # The hostname (2nd arg) must be the one of player 0, i.e. "mpcnode0"
    command: ["wait-for-it", "ethnode:8545", "--", "bash", "mpc-node.sh", "0", "ethnode", "mpcnode0"]

  mpcnode1:
    image: sbellem/hbswap
    environment:
      POA_KEYSTORE: /opt/poa/keystore
    ports:
      - 8080:8080
    volumes:
      - mpc-bytecodes:/usr/src/hbswap/Programs/Bytecode
      - mpc-schedules:/usr/src/hbswap/Programs/Schedules
    secrets:
      - P1.key
    working_dir: /usr/src/hbswap
    # NOTE IMPORTANT!
    # The hostname (2nd arg) must be the one of player 0, i.e. "mpcnode0"
    command: ["wait-for-it", "ethnode:8545", "--", "bash", "mpc-node.sh", "1", "ethnode", "mpcnode0"]

  mpcnode2:
    image: sbellem/hbswap
    environment:
      POA_KEYSTORE: /opt/poa/keystore
    ports:
      - 8080:8080
    volumes:
      - mpc-bytecodes:/usr/src/hbswap/Programs/Bytecode
      - mpc-schedules:/usr/src/hbswap/Programs/Schedules
    secrets:
      - P2.key
    working_dir: /usr/src/hbswap
    # NOTE IMPORTANT!
    # The hostname (2nd arg) must be the one of player 0, i.e. "mpcnode0"
    command: ["wait-for-it", "ethnode:8545", "--", "bash", "mpc-node.sh", "2", "ethnode", "mpcnode0"]

  mpcnode3:
    image: sbellem/hbswap
    environment:
      POA_KEYSTORE: /opt/poa/keystore
    ports:
      - 8080:8080
    volumes:
      - mpc-bytecodes:/usr/src/hbswap/Programs/Bytecode
      - mpc-schedules:/usr/src/hbswap/Programs/Schedules
    secrets:
      - P3.key
    working_dir: /usr/src/hbswap
    # NOTE IMPORTANT!
    # The hostname (2nd arg) must be the one of player 0, i.e. "mpcnode0"
    command: ["wait-for-it", "ethnode:8545", "--", "bash", "mpc-node.sh", "3", "ethnode", "mpcnode0"]

#secrets:
#   P0.key:
#     name: arn:aws:secretsmanager:eu-west-3:809684608753:secret:mpcnode0_key-3qSj9V
#     external: true
#   P1.key:
#     name: arn:aws:secretsmanager:eu-west-3:809684608753:secret:mpcnode1_key-F51Z10
#     external: true
#   P2.key:
#     name: arn:aws:secretsmanager:eu-west-3:809684608753:secret:mpcnode2_key-KZKRwI
#     external: true
#   P3.key:
#     name: arn:aws:secretsmanager:eu-west-3:809684608753:secret:mpcnode3_key-qEEByY
#     external: true

secrets:
   P0.key:
     file: secrets/P0.key
   P1.key:
     file: secrets/P1.key
   P2.key:
     file: secrets/P2.key
   P3.key:
     file: secrets/P3.key
