# MPC network configuation

# MPC network params
N = 4
T = 1
# IMPORTANT!
# The leader Hostname be the one of MPC player 0
LeaderHostname = "mpcnode0"

[EthNode]
Network = "testnet"
Hostname = "kovan.infura.io"
HttpEndpoint = "https://kovan.infura.io/v3/6a82d2519efb4d748c02552e02e369c1"
WsEndpoint   = "wss://kovan.infura.io/ws/v3/6a82d2519efb4d748c02552e02e369c1"
HttpPort = 8545
WsPort  = 8546

# MPC servers
[[Servers]]
id = 0
Host = "mpcnode0"
HttpPort = 8080
HttpHost = "0.0.0.0"

[[Servers]]
id = 1
Host = "mpcnode1"
HttpPort = 8081
HttpHost = "0.0.0.0"

[[Servers]]
id = 2
Host = "mpcnode2"
HttpPort = 8082
HttpHost = "0.0.0.0"

[[Servers]]
id = 3
Host = "mpcnode3"
HttpPort = 8083
HttpHost = "0.0.0.0"
