version: '3.8'

services:

  deploy.contract:
    image: hbswap-go-z
    build:
      context: .
      dockerfile: contract.Dockerfile
      target: deploy
    environment:
      POADIR: /opt/poa
      POA_KEYSTORE: /opt/poa/keystore
    working_dir: /go/src/github.com/initc3/MP-SPDZ/Scripts/hbswap/go
    volumes:
      - ./poa:/opt/poa
      - ./src:/go/src/github.com/initc3/MP-SPDZ/Scripts/hbswap
    entrypoint: ""
    #command: ["wait-for-it", "eth.chain:8545", "--", "go", "run", "deploy/deploy.go", "eth.chain"]
    command: ["go", "run", "deploy/deploy.go", "honey-LoadB-2JZ1BRZY8F3Q-3085a0a161f4eb3d.elb.eu-west-3.amazonaws.com"]
