version: '3.8'

services:

  deploycontract:
    image: hbswap-go
    build:
      context: .
      dockerfile: Dockerfile
      target: go-deps
    environment:
      POADIR: /opt/poa
      POA_KEYSTORE: /opt/poa/keystore
    working_dir: /go/src/github.com/initc3/HoneyBadgerSwap/src/go
    volumes:
      - ./poa:/opt/poa
      #- ./poa/keystore:/opt/poa/keystore
      - ./src:/go/src/github.com/initc3/HoneyBadgerSwap/src
    entrypoint: ""
    command: ["go", "run", "deploy/deploy.go", "$HBSWAP_ETHNODE"]
    #command: ["go", "run", "deploy/deploy.go", "aws-LoadBal-1I36V77N4SFN4-705c9573e0b2603c.elb.eu-west-3.amazonaws.com"]
    #command: ["go", "run", "deploy/deploy.go", "hbswa-LoadB-1WFZ8C0UK3GUR-673e08abd4c66d64.elb.eu-west-3.amazonaws.com"]

