version: '3.8'

networks:
  hbswap:

volumes:
  mpc-bytecodes:
  mpc-schedules:
  public-keys:
  secrets-p0:
  secrets-p1:
  secrets-p2:
  secrets-p3:
  inputmaskshares-p0:
  inputmaskshares-p1:
  inputmaskshares-p2:
  inputmaskshares-p3:
  ppdata-p0:
  ppdata-p1:
  ppdata-p2:
  ppdata-p3:
  persistence-p0:
  persistence-p1:
  persistence-p2:
  persistence-p3:
  db-p0:
  db-p1:
  db-p2:
  db-p3:

services:

  mpcnode0:
    image: hbswap
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POADIR: /opt/poa
      POA_KEYSTORE: /opt/poa/keystore
      PYTHONUNBUFFERED: 1
    ports:
      - 58080:8080
    networks:
      - hbswap
    volumes:
      - mpc-bytecodes:/usr/src/hbswap/Programs/Bytecode
      - mpc-schedules:/usr/src/hbswap/Programs/Schedules
      - ./conf/server.toml:/opt/hbswap/conf/server.toml
      - ./scripts/mpc-node-testnet.sh:/usr/src/hbswap/mpc-node-testnet.sh
      - ./scripts/wait-for-it.sh:/usr/local/bin/wait-for-it
      - ./src:/go/src/github.com/initc3/HoneyBadgerSwap/src
      - public-keys:/opt/hbswap/public-keys:ro
      - secrets-p0:/opt/hbswap/secrets
      - ./poa:/opt/poa
      - ./log:/usr/src/hbswap/log
      - ./src/python:/usr/src/honeybadgerswap-python
        #- inputmaskshares-p0:/opt/hbswap/inputmask-shares
        #- ppdata-p0:/opt/hbswap/preprocessing-data
        #- persistence-p0:/usr/src/hbswap/Persistence
    working_dir: /usr/src/hbswap
    # NOTE IMPORTANT!
    # The hostname (2nd arg) must be the one of player 0, i.e. "mpcnode0"
    command: ["bash", "mpc-node-testnet.sh", "0", "mpcnode0"]

  mpcnode1:
    image: hbswap
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POADIR: /opt/poa
      POA_KEYSTORE: /opt/poa/keystore
      PYTHONUNBUFFERED: 1
    ports:
      - 58081:8080
    networks:
      - hbswap
    volumes:
      - mpc-bytecodes:/usr/src/hbswap/Programs/Bytecode
      - mpc-schedules:/usr/src/hbswap/Programs/Schedules
      - ./conf/server.toml:/opt/hbswap/conf/server.toml
      - ./scripts/mpc-node-testnet.sh:/usr/src/hbswap/mpc-node-testnet.sh
      - ./scripts/wait-for-it.sh:/usr/local/bin/wait-for-it
      - ./src:/go/src/github.com/initc3/HoneyBadgerSwap/src
      - public-keys:/opt/hbswap/public-keys:ro
      - secrets-p1:/opt/hbswap/secrets
      - ./poa:/opt/poa
      - ./log:/usr/src/hbswap/log
      - ./src/python:/usr/src/honeybadgerswap-python
    working_dir: /usr/src/hbswap
    # NOTE IMPORTANT!
    # The hostname (2nd arg) must be the one of player 0, i.e. "mpcnode0"
    command: ["bash", "mpc-node-testnet.sh", "1", "mpcnode0"]

  mpcnode2:
    image: hbswap
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POADIR: /opt/poa
      POA_KEYSTORE: /opt/poa/keystore
      PYTHONUNBUFFERED: 1
    ports:
      - 58082:8080
    networks:
      - hbswap
    volumes:
      - mpc-bytecodes:/usr/src/hbswap/Programs/Bytecode
      - mpc-schedules:/usr/src/hbswap/Programs/Schedules
      - ./conf/server.toml:/opt/hbswap/conf/server.toml
      - ./scripts/mpc-node-testnet.sh:/usr/src/hbswap/mpc-node-testnet.sh
      - ./scripts/wait-for-it.sh:/usr/local/bin/wait-for-it
      - ./src:/go/src/github.com/initc3/HoneyBadgerSwap/src
      - public-keys:/opt/hbswap/public-keys:ro
      - secrets-p2:/opt/hbswap/secrets
      - ./poa:/opt/poa
      - ./log:/usr/src/hbswap/log
      - ./src/python:/usr/src/honeybadgerswap-python
    working_dir: /usr/src/hbswap
    # NOTE IMPORTANT!
    # The hostname (2nd arg) must be the one of player 0, i.e. "mpcnode0"
    command: ["bash", "mpc-node-testnet.sh", "2", "mpcnode0"]

  mpcnode3:
    image: hbswap
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POADIR: /opt/poa
      POA_KEYSTORE: /opt/poa/keystore
      PYTHONUNBUFFERED: 1
    ports:
      - 58083:8080
    networks:
      - hbswap
    volumes:
      - mpc-bytecodes:/usr/src/hbswap/Programs/Bytecode
      - mpc-schedules:/usr/src/hbswap/Programs/Schedules
      - ./conf/server.toml:/opt/hbswap/conf/server.toml
      - ./scripts/mpc-node-testnet.sh:/usr/src/hbswap/mpc-node-testnet.sh
      - ./scripts/wait-for-it.sh:/usr/local/bin/wait-for-it
      - ./src:/go/src/github.com/initc3/HoneyBadgerSwap/src
      - public-keys:/opt/hbswap/public-keys:ro
      - secrets-p3:/opt/hbswap/secrets
      - ./poa:/opt/poa
      - ./log:/usr/src/hbswap/log
      - ./src/python:/usr/src/honeybadgerswap-python
    working_dir: /usr/src/hbswap
    # NOTE IMPORTANT!
    # The hostname (2nd arg) must be the one of player 0, i.e. "mpcnode0"
    command: ["bash", "mpc-node-testnet.sh", "3", "mpcnode0"]
