version: '3.8'

services:

  dev:
    image: hbswap:latest
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    volumes:
      - ./ratel:/usr/src/hbswap/ratel
      - ./scripts/chain-latest.sh:/usr/src/hbswap/chain-latest.sh
      - ./scripts/latency-control.sh:/usr/src/hbswap/latency-control.sh
      - ./poa:/opt/poa
      - ./ratel/genfiles/mpc:/usr/src/hbswap//Programs/Source
    working_dir: /usr/src/hbswap
    command: tail -F anything
