version: '3.8'

services:
  public.deposit:
    image: hbswap-go
    build:
      context: .
      dockerfile: Dockerfile
      target: go-deps
    environment:
      POADIR: /opt/poa
      POA_KEYSTORE: /opt/poa/keystore
      #networks:
      #  - hbswap
    working_dir: /usr/src/scripts
    volumes:
      - ./poa:/opt/poa
      - ./scripts/wait-for-it.sh:/usr/local/bin/wait-for-it
      - ./scripts:/usr/src/scripts
      - ./src:/go/src/github.com/initc3/HoneyBadgerSwap/src
    entrypoint: ""
    # TODO wait for contract to be deployed/available
    #command: ["bash", "client-public-deposit.sh", "ethnode"]
    command: ["bash", "client-public-deposit.sh", "aws-LoadBal-1RRRLSMSRJ72-54a6aeb93abec510.elb.eu-west-3.amazonaws.com"]

  secret.deposit:
    image: hbswap-go
    build:
      context: .
      dockerfile: Dockerfile
      target: go-deps
    environment:
      POADIR: /opt/poa
      POA_KEYSTORE: /opt/poa/keystore
      #networks:
      #  - hbswap
    working_dir: /usr/src/scripts
    volumes:
      - ./poa:/opt/poa
      - ./scripts/wait-for-it.sh:/usr/local/bin/wait-for-it
      - ./scripts:/usr/src/scripts
      - ./src:/go/src/github.com/initc3/HoneyBadgerSwap/src
    entrypoint: ""
    # TODO wait for contract to be deployed/available
    #command: ["bash", "client-secret-deposit.sh", "ethnode"]
    command: ["bash", "client-secret-deposit.sh", "aws-LoadBal-1RRRLSMSRJ72-54a6aeb93abec510.elb.eu-west-3.amazonaws.com"]

  trade-1:
    image: hbswap
    build:
      context: .
      dockerfile: Dockerfile
    # FIXME is the poa stuff needed?
    environment:
      POADIR: /opt/poa
      POA_KEYSTORE: /opt/poa/keystore
      #networks:
      #  - hbswap
    # FIXME is the poa stuff needed?
    volumes:
      - ./poa:/opt/poa
      - ./conf/client.toml:/opt/hbswap/conf/client.toml
      - ./scripts:/usr/src/scripts
      - ./scripts/wait-for-it.sh:/usr/local/bin/wait-for-it
      - ./src:/go/src/github.com/initc3/HoneyBadgerSwap/src
    working_dir: /usr/src/scripts
    #command: ["wait-for-it", "mpcnode3:8080", "--", "bash", "trade-1.sh", "ethnode"]
    command: ["bash", "trade-1.sh", "aws-LoadBal-1RRRLSMSRJ72-54a6aeb93abec510.elb.eu-west-3.amazonaws.com"]
    #command: ["wait-for-it", "mpcnode3:8080", "--", "bash", "trade.sh", "ethnode", "0", "1.1", "-2.5"]
    #command: ["wait-for-it", "mpcnode3:8080", "--", "bash", "trade.sh", "ethnode", "0", "-1.1", "2"]

  trade-2:
    image: hbswap
    build:
      context: .
      dockerfile: Dockerfile
    # FIXME is the poa stuff needed?
    environment:
      POADIR: /opt/poa
      POA_KEYSTORE: /opt/poa/keystore
      #networks:
      #  - hbswap
    # FIXME is the poa stuff needed?
    volumes:
      - ./poa:/opt/poa
      - ./conf/client.toml:/opt/hbswap/conf/client.toml
      - ./scripts:/usr/src/scripts
      - ./scripts/wait-for-it.sh:/usr/local/bin/wait-for-it
      - ./src:/go/src/github.com/initc3/HoneyBadgerSwap/src
    working_dir: /usr/src/scripts
    #command: ["wait-for-it", "mpcnode3:8080", "--", "bash", "trade-2.sh", "ethnode"]
    command: ["bash", "trade-2.sh", "aws-LoadBal-1RRRLSMSRJ72-54a6aeb93abec510.elb.eu-west-3.amazonaws.com"]
