# MPC network configuation

# MPC network params
N = 4
T = 1

[EthNode]
Network = "testnet"
Hostname = "kovan.infura.io"
HttpEndpoint = "https://kovan.infura.io/v3/6a82d2519efb4d748c02552e02e369c1"
WsEndpoint   = "wss://kovan.infura.io/ws/v3/6a82d2519efb4d748c02552e02e369c1"
HttpPort = 8545
WsPort  = 8546

# MPC servers
[[Servers]]
Id = 0
Host = "aws-LoadBal-R49TXS4T9EHY-c65ef0263445cee0.elb.eu-west-3.amazonaws.com"
HttpPort = 8080

[[Servers]]
Id = 1
Host = "aws-LoadBal-R49TXS4T9EHY-c65ef0263445cee0.elb.eu-west-3.amazonaws.com"
HttpPort = 8081

[[Servers]]
Id = 2
Host = "aws-LoadBal-R49TXS4T9EHY-c65ef0263445cee0.elb.eu-west-3.amazonaws.com"
HttpPort = 8082

[[Servers]]
Id = 3
Host = "aws-LoadBal-R49TXS4T9EHY-c65ef0263445cee0.elb.eu-west-3.amazonaws.com"
HttpPort = 8083
