# MPC network configuation

# MPC network params
N = 4
T = 1

# MPC servers
[[Servers]]
Id = 0
Host = "aws-LoadBal-1VP1WJT5CUI8T-43b39cb4a8b33309.elb.eu-west-3.amazonaws.com"
HttpPort = 8080

[[Servers]]
Id = 1
Host = "aws-LoadBal-1VP1WJT5CUI8T-43b39cb4a8b33309.elb.eu-west-3.amazonaws.com"
HttpPort = 8081

[[Servers]]
Id = 2
Host = "aws-LoadBal-1VP1WJT5CUI8T-43b39cb4a8b33309.elb.eu-west-3.amazonaws.com"
HttpPort = 8082

[[Servers]]
Id = 3
Host = "aws-LoadBal-1VP1WJT5CUI8T-43b39cb4a8b33309.elb.eu-west-3.amazonaws.com"
HttpPort = 8083
