# MPC network configuation

# MPC network params
n = 4
t = 1

# MPC servers
[[servers]]
id = 0
host = "aws-LoadBal-1VP1WJT5CUI8T-43b39cb4a8b33309.elb.eu-west-3.amazonaws.com"
http_port = 8080

[[servers]]
id = 1
host = "aws-LoadBal-1VP1WJT5CUI8T-43b39cb4a8b33309.elb.eu-west-3.amazonaws.com"
http_port = 8081

[[servers]]
id = 2
host = "aws-LoadBal-1VP1WJT5CUI8T-43b39cb4a8b33309.elb.eu-west-3.amazonaws.com"
http_port = 8082

[[servers]]
id = 3
host = "aws-LoadBal-1VP1WJT5CUI8T-43b39cb4a8b33309.elb.eu-west-3.amazonaws.com"
http_port = 8083
