version: '3.8'

services:

  mpcnode0:
    image: hbswap:local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 58123:8123
    volumes:
      - ./src/python:/usr/src/honeybadgerswap-python
      - ./poa/keystore:/opt/poa/keystore
    secrets:
      - P0.key
    working_dir: /usr/src/honeybadgerswap-python/honeybadgerswap/server
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8123"]
