version: '3.8'

volumes:
  public-keys:
  secrets-p0:
  secrets-p1:
  secrets-p2:
  secrets-p3:

services:
  mpc.trusted.setup:
    image: hbswap-setup
    build:
      context: .
      dockerfile: setup.Dockerfile
    volumes:
      - ../../Scripts/setup-ssl.sh:/usr/src/setup-ssl.sh
      - ./scripts/generate-keys.sh:/usr/src/generate-keys.sh
      - public-keys:/usr/src/Player-Data
      - secrets-p0:/usr/src/Secrets-P0
      - secrets-p1:/usr/src/Secrets-P1
      - secrets-p2:/usr/src/Secrets-P2
      - secrets-p3:/usr/src/Secrets-P3
    #command: ["bash", "setup-ssl.sh", "4"]
    working_dir: /usr/src
    command: ["bash", "generate-keys.sh", "setup-ssl.sh", "4"]

  # compile MPC programs (hbswap_init, hbswap_trade_prep, hbswap_trade)
  # see scripts/compile.sh for details
  mpc.compile:
    image: python:3.8
    volumes:
      - ../../compile.py:/usr/src/compile.py
      - ../../Compiler:/usr/src/Compiler
      - ../../Programs:/usr/src/Programs
      - ./scripts/compile.sh:/usr/src/compile.sh
    working_dir: /usr/src
    command: ["bash", "compile.sh"]
