name: ci-build-image

on:
  pull_request:
    branches: [ main, ci, dev ]

  workflow_dispatch:

jobs:
  just_build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set Short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build docker image for HoneyBadgerSwap
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            initc3/honeybadgerswap,
            initc3/honeybadgerswap:${{ steps.vars.outputs.short_sha }}
